region="europe-west4"
project_id="x"
zone-01="europe-west4-a"
zone-02="europe-west4-b"
zone-03="europe-west4-c"
vpc_name="prd-vpc"
subnet_name_01="prd-sub-01"
cluster_name_01="cluster-01"
node_pool_name_01="node-pool-01"

